git mv jesttest1.PNG jesttest1.png
git mv jesttest1b.PNG jesttest1b.png
git mv jesttest2.PNG jesttest2.png
git mv jesttest2b.PNG jesttest2b.png
git mv jesttest3.PNG jesttest3.png
git mv jesttest3b.PNG jesttest3b.png
git mv jesttest4.PNG jesttest4.png
git mv jesttest4b.PNG jesttest4b.png
git mv problem10.PNG problem10.png
git mv problem10b.PNG problem10b.png
git mv problem11.PNG problem11.png
git mv problem11b.PNG problem11b.png
git mv problem11c.PNG problem11c.png
git mv problem12.PNG problem12.png
git mv problem13.PNG problem13.png
git mv problem1fixed.PNG problem1fixed.png
git mv problem2.PNG problem2.png
git mv problem2fixed.PNG problem2fixed.png
git mv problem3.PNG problem3.png
git mv problem3fixed.PNG problem3fixed.png
git mv problem4.PNG problem4.png
git mv problem4b.PNG problem4b.png
git mv problem4c.PNG problem4c.png
git mv problem5.PNG problem5.png
git mv problem6.PNG problem6.png
git mv problem7.PNG problem7.png
git mv problem7b.PNG problem7b.png
git mv problem8.PNG problem8.png
git mv problem8b.PNG problem8b.png
git mv wireframe-boss1.PNG wireframe-boss1.png
git mv wireframe-boss2-large.PNG wireframe-boss2-large.png
git mv wireframe-boss2.PNG wireframe-boss2.png
git mv wireframe-large-screen.PNG wireframe-large-screen.png
git mv wireframe-small-screen.PNG wireframe-small-screen.png
